# Generated by Django 4.1 on 2022-12-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_passwrod_signup_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='emial',
            new_name='email',
        ),
    ]
