# Generated by Django 4.1 on 2022-12-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_emial_signup_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
