# Generated by Django 4.1 on 2022-10-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
