# Generated by Django 4.1 on 2022-09-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_data_post_published_data_post_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['status']},
        ),
    ]
