# Generated by Django 4.1 on 2022-09-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/2switch.png', upload_to='blog/'),
        ),
    ]
