# Generated by Django 4.1 on 2022-10-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag',
        ),
    ]
