# Generated by Django 4.1 on 2022-10-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_tags_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
