# Generated by Django 4.1 on 2022-10-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_tag_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
