# Generated by Django 4.1 on 2022-10-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approach',
            new_name='approved',
        ),
    ]
