# Generated by Django 4.1 on 2022-11-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_post_login_require'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='login_require',
            new_name='need_to_login',
        ),
    ]
